### ISSUE TITLE
Succesfull DotPay transaction doesn't change order status

### ISSUE THREAD

**Issue by pawelad** [cypreess/django-getpaid#88] opened 2015-11-16 21:39 UTC
Hi,

I'm having problems with getting the succesfull signal back from DotPay transaction and I was wondering if anyone could help me debug it.
Everything works well on `dummy` buckend, but after switching to `dotpay` I can't get the order status changed from `in progress` to `paid`.

Thanks in advance

**Comment by pawciobiel** [comment] 2015-11-16 23:16
duplicate of #89

**Closed by pawciobiel** 2015-11-16 23:16 UTC

**Comment by pawelad** [comment] 2015-11-17 08:01
Sorry for the duplicate, my browser crashed while hitting submit and I assumed it wasn't posted.

**Comment by pawciobiel** [comment] 2015-11-17 09:07
no worries
